[project]
name = "philip"
version = "0.1.0"
description = "Wahrscheinlichkeitsrechner fÃ¼r kartenbasiertes P&P-System"
requires-python = ">=3.10.0"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
]
